In [3]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.neighbors import NearestNeighbors

# Dataset as matrix
X = np.array([
    [10, 200, 2],   # Provider 1
    [7, 120, 1],    # Provider 2
    [3, 50, 4],     # Provider 3
    [12, 300, 3]    # Provider 4
])

print("Original Dataset:\n", X)

# ---- Preprocessing: MinMax Scaling ----
scaler = MinMaxScaler()
print("scaler",scaler)
X_scaled = MinMaxScaler().fit_transform(X)
print("\nScaled Dataset (0-1 range):\n", X_scaled)

# ---- Simple ML Connection: Find nearest provider to P1 ----
neighbors = NearestNeighbors(n_neighbors=2, metric="euclidean")  # find 1 nearest neighbor
neighbors.fit(X_scaled)
distances, indices = neighbors.kneighbors([X_scaled[0]])  # compare P1
print("\nNearest neighbor to Provider 1 is Provider:", indices[0][1]+1, 
      "with distance:", distances[0][1])


Original Dataset:
 [[ 10 200   2]
 [  7 120   1]
 [  3  50   4]
 [ 12 300   3]]
scaler MinMaxScaler()

Scaled Dataset (0-1 range):
 [[0.77777778 0.6        0.33333333]
 [0.44444444 0.28       0.        ]
 [0.         0.         1.        ]
 [1.         1.         0.66666667]]

Nearest neighbor to Provider 1 is Provider: 4 with distance: 0.5661217423491999


In [4]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import euclidean_distances

# Dataset
X = np.array([
    [10, 200, 2],
    [7, 120, 1],
    [3, 50, 4],
    [12, 300, 3]
])

# Distances before scaling
dist_before = euclidean_distances(X, X)

# MinMax Scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Distances after scaling
dist_after = euclidean_distances(X_scaled, X_scaled)

print("Distances BEFORE scaling:\n", np.round(dist_before, 2))
print("\nDistances AFTER scaling:\n", np.round(dist_after, 2))


Distances BEFORE scaling:
 [[  0.    80.06 150.18 100.02]
 [ 80.06   0.    70.18 180.08]
 [150.18  70.18   0.   250.16]
 [100.02 180.08 250.16   0.  ]]

Distances AFTER scaling:
 [[0.   0.57 1.19 0.57]
 [0.57 0.   1.13 1.13]
 [1.19 1.13 0.   1.45]
 [0.57 1.13 1.45 0.  ]]


In [5]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

# Dataset
X = np.array([
    [10, 200, 2],  # P1
    [7, 120, 1],   # P2
    [3, 50, 4],    # P3
    [12, 300, 3]   # P4
])
y = np.array([0, 0, 1, 1])  # labels

# New provider
X_new = np.array([[8, 220, 2]])

# --- Case 1: Without Scaling ---
knn_raw = KNeighborsClassifier(n_neighbors=1, metric="euclidean")
knn_raw.fit(X, y)
pred_raw = knn_raw.predict(X_new)

# --- Case 2: With Scaling ---
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_new_scaled = scaler.transform(X_new)

knn_scaled = KNeighborsClassifier(n_neighbors=1, metric="euclidean")
knn_scaled.fit(X_scaled, y)
pred_scaled = knn_scaled.predict(X_new_scaled)

print("Prediction WITHOUT scaling:", pred_raw[0])
print("Prediction WITH scaling:", pred_scaled[0])


Prediction WITHOUT scaling: 0
Prediction WITH scaling: 0


In [ ]:
def matrix_add(A, B):
    # check same dimensions
    if len(A) != len(B) or len(A[0]) != len(B[0]):
        raise ValueError("Matrices must have same shape for addition")
    
    result = []
    for i in range(len(A)):  # loop rows
        row = []
        for j in range(len(A[0])):  # loop columns
            row.append(A[i][j] + B[i][j])
        result.append(row)
    return result


In [ ]:
def scalar_multiply(k, A):
    result = []
    for i in range(len(A)):      # rows
        row = []
        for j in range(len(A[0])):  # cols
            row.append(k * A[i][j])
        result.append(row)
    return result


In [6]:
# Provider dataset as matrix
X = [
    [10, 200],  # P1
    [7, 120],   # P2
    [3, 50]     # P3
]

# Another dataset (maybe updated patient counts)
Y = [
    [2, 30],
    [1, 20],
    [0, 10]
]

# Matrix Addition: combine X + Y
C = matrix_add(X, Y)
print("X + Y =")
for row in C:
    print(row)

# Scalar Multiplication: double the dataset
D = scalar_multiply(2, X)
print("\n2 * X =")
for row in D:
    print(row)


NameError: name 'matrix_add' is not defined